#Mysql Persitance Data
mysql-data:
 image: busybox
 container_name: mysql-data
 volumes:
  - /var/lib/mysql:/var/lib/mysql

#Mysql Container
mysql:
 image: mysql
 container_name: mysql
 hostname: mysql
 volumes_from:
  - mysql-data
 env_file:
  - ./mysql.env

#GLPI Container
glpi:
 image: diouxx/glpi
 container_name : glpi
 hostname: glpi
 ports:
  - "80:80"
 links:
  - mysql:mysql
